version: "1.0"
projectName: Kvv_1908_AWSTestProject
runtimes:
- runtimeAlias: Cloud Designtime
  assets:
  - name: alert Workflow
    type: workflow
    uid: fl17d539a8d631443d83a30167c544de4f
    stepId: a0
    reference: project.kvv_1908_awstest.integrations:AlertsCRTandERT
- runtimeAlias: kvv_1908_AWSTest
  assets:
  - name: alert Workflow
    type: workflow
    uid: fl17d539a8d631443d83a30167c544de4f
    stepId: a1
    reference: project.kvv_1908_awstest.integrations:AlertsCRTandERT
  - name: fld_111957447_stage00.projects.fl697903005a6d43348f4282033b8eec72.integrations:tppdb
    type: flow
    stepId: /0
    reference: fld_111957447_stage00.projects.fl697903005a6d43348f4282033b8eec72.WmPackageServiceProvider.SIQAJDBCAdapterTests.adapterServices:getData
